version: '1.0'
name: dtk-build-ccc-app-manager-20220829
displayName: dtk-build-ccc-app-manager
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
  pr:
    branches:
      prefix:
        - ''
variables:
  global:
    - WORK_FLOW_ENV_PKG_VERSION
stages:
  - name: stage-c9e7dc6d
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: dtk-build
        displayName: Dtk build
        nodeVersion: 17.8.0
        commands:
          - pwd
          - WORK_DIR=`pwd`
          - echo "获取Debian 10环境"
          - cd /mnt/
          - git clone https://gitee.com/ct243768648/debian-10-container.git
          - tar -xf debian-10-container/Debian-10_part1.tar
          - tar -xf debian-10-container/Debian-10_part2.tar
          - tar -xf debian-10-container/Debian-10_part3.tar
          - rm -rf debian-10-container
          - echo "将代码拷贝到 Debian 10 环境根目录"
          - cp -r $WORK_DIR Debian-10/gitee-go-build
          - wget https://gitee.com/ct243768648/ccc-app-manager/raw/main/build-on-gitee.sh
          - mv build-on-gitee.sh Debian-10
          - chmod +x Debian-10/build-on-gitee.sh
          - ls Debian-10
          - echo "进入Debian 10环境"
          - chroot /mnt/Debian-10 /bin/bash /build-on-gitee.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - /mnt/Debian-10/target
        caches: []
        notify: []
        strategy:
          retry: '0'
  - name: stage-421e5f07
    displayName: 上传
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
